version: '3.8'

services:
  # Etcd cluster for distributed configuration
  etcd0:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_NAME=etcd0
    networks:
      - patroni-network
    volumes:
      - etcd0-data:/bitnami/etcd

  etcd1:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_NAME=etcd1
    networks:
      - patroni-network
    volumes:
      - etcd1-data:/bitnami/etcd

  etcd2:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_NAME=etcd2
    networks:
      - patroni-network
    volumes:
      - etcd2-data:/bitnami/etcd

  # Patroni PostgreSQL nodes
  patroni1:
    image: d2cio/patroni
    build:
      context: .
      dockerfile: Dockerfile.patroni
    environment:
      - PATRONI_NAME=patroni1
      - PATRONI_SCOPE=postgres
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni1:5432
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replicatorpass
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=postgrespass
      - PATRONI_ETCD_HOST=etcd0:2379,etcd1:2379,etcd2:2379
    networks:
      - patroni-network
    volumes:
      - patroni1-data:/var/lib/postgresql/data
    depends_on:
      - etcd0
      - etcd1
      - etcd2

  patroni2:
    image: d2cio/patroni
    build:
      context: .
      dockerfile: Dockerfile.patroni
    environment:
      - PATRONI_NAME=patroni2
      - PATRONI_SCOPE=postgres
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni2:5432
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replicatorpass
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=postgrespass
      - PATRONI_ETCD_HOST=etcd0:2379,etcd1:2379,etcd2:2379
    networks:
      - patroni-network
    volumes:
      - patroni2-data:/var/lib/postgresql/data
    depends_on:
      - etcd0
      - etcd1
      - etcd2

  patroni3:
    image: d2cio/patroni
    build:
      context: .
      dockerfile: Dockerfile.patroni
    environment:
      - PATRONI_NAME=patroni3
      - PATRONI_SCOPE=postgres
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni3:5432
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replicatorpass
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=postgrespass
      - PATRONI_ETCD_HOST=etcd0:2379,etcd1:2379,etcd2:2379
    networks:
      - patroni-network
    volumes:
      - patroni3-data:/var/lib/postgresql/data
    depends_on:
      - etcd0
      - etcd1
      - etcd2

  # HAProxy for load balancing
  haproxy:
    image: haproxy:latest
    ports:
      - "5000:5000"
      - "7000:7000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - patroni-network
    depends_on:
      - patroni1
      - patroni2
      - patroni3

networks:
  patroni-network:
    driver: bridge

volumes:
  etcd0-data:
  etcd1-data:
  etcd2-data:
  patroni1-data:
  patroni2-data:
  patroni3-data: 